"""APT repository setup helper functions.
APT 저장소 설정 헬퍼 함수.
"""

import os
import shutil
import subprocess
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt
from rich.table import Table

console = Console()

# Constants
APT_BASE = Path("/var/www/apt")
APT_REPO = APT_BASE / "repo"
APT_GPG_HOME = APT_BASE / ".gnupg"
APT_CONFIG_FILE = APT_BASE / ".config"


def _check_root(command: str) -> None:
    """Check root privilege."""
    if os.geteuid() != 0:
        console.print(f"[red]✗[/red] Root privilege required.")
        console.print(f"  Run: sudo vaultctl admin {command}")
        raise typer.Exit(1)


def _load_apt_config() -> dict:
    """Load existing APT config."""
    if not APT_CONFIG_FILE.exists():
        return {}
    
    config = {}
    for line in APT_CONFIG_FILE.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, value = line.split("=", 1)
            config[key.strip()] = value.strip().strip('"')
    return config


def _save_apt_config(config: dict) -> None:
    """Save APT config."""
    APT_BASE.mkdir(parents=True, exist_ok=True)
    
    content = f"""# APT Repository Configuration
# Generated by vaultctl admin setup apt-server

DOMAIN={config.get('DOMAIN', '')}
GPG_EMAIL={config.get('GPG_EMAIL', '')}
GPG_NAME={config.get('GPG_NAME', '')}
GPG_KEY_ID={config.get('GPG_KEY_ID', '')}
REPO_NAME={config.get('REPO_NAME', '')}
REPO_LABEL={config.get('REPO_LABEL', '')}
REPO_CODENAME={config.get('REPO_CODENAME', '')}
REPO_ARCH={config.get('REPO_ARCH', '')}
ENABLE_AUTH={config.get('ENABLE_AUTH', 'false')}
AUTH_USER={config.get('AUTH_USER', '')}
AUTH_PASS={config.get('AUTH_PASS', '')}
WEB_SERVER={config.get('WEB_SERVER', '')}
LISTEN_PORT={config.get('LISTEN_PORT', '8080')}
"""
    APT_CONFIG_FILE.write_text(content)
    APT_CONFIG_FILE.chmod(0o600)


def _get_gpg_key_id() -> Optional[str]:
    """Get GPG key ID."""
    result = subprocess.run(
        ["gpg", "--list-keys", "--with-colons"],
        capture_output=True,
        text=True,
    )
    
    for line in result.stdout.splitlines():
        if line.startswith("pub:"):
            parts = line.split(":")
            if len(parts) > 4:
                return parts[4][-8:]
    
    return None


def _install_caddy() -> None:
    """Install Caddy web server."""
    if shutil.which("caddy"):
        console.print("[green]✓[/green] Caddy already installed")
        return
    
    console.print("[dim]Installing Caddy...[/dim]")
    subprocess.run([
        "bash", "-c",
        "curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | "
        "gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg"
    ], check=True)
    subprocess.run([
        "bash", "-c",
        "curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | "
        "tee /etc/apt/sources.list.d/caddy-stable.list > /dev/null"
    ], check=True)
    subprocess.run(["apt-get", "update", "-qq"], check=True)
    subprocess.run(["apt-get", "install", "-y", "-qq", "caddy"], check=True)


def _setup_apt_gpg(config: dict) -> None:
    """Setup GPG key for APT signing."""
    console.print("\n[bold]Setting up GPG key...[/bold]")
    
    os.environ["GNUPGHOME"] = str(APT_GPG_HOME)
    
    result = subprocess.run(
        ["gpg", "--list-keys", config["GPG_EMAIL"]],
        capture_output=True,
    )
    
    if result.returncode == 0:
        console.print(f"[green]✓[/green] Existing GPG key found: {config['GPG_EMAIL']}")
    else:
        console.print("[dim]Generating new GPG key (this may take a while)...[/dim]")
        
        batch_content = f"""%echo Generating APT signing key
Key-Type: RSA
Key-Length: 4096
Subkey-Type: RSA
Subkey-Length: 4096
Name-Real: {config["GPG_NAME"]}
Name-Email: {config["GPG_EMAIL"]}
Expire-Date: 0
%no-protection
%commit
%echo Done
"""
        batch_file = Path("/tmp/gpg-batch")
        batch_file.write_text(batch_content)
        
        subprocess.run(["gpg", "--batch", "--gen-key", str(batch_file)], check=True)
        batch_file.unlink()
        console.print("[green]✓[/green] GPG key generated")
    
    gpg_key_id = _get_gpg_key_id()
    
    if not gpg_key_id:
        console.print("[red]✗[/red] Failed to get GPG key ID")
        raise typer.Exit(1)
    
    config["GPG_KEY_ID"] = gpg_key_id
    console.print(f"  Key ID: {gpg_key_id}")
    
    subprocess.run(
        ["gpg", "--armor", "--export"],
        stdout=open(APT_REPO / "key.gpg", "w"),
        check=True,
    )
    subprocess.run(
        ["gpg", "--export"],
        stdout=open(APT_REPO / "key", "wb"),
        check=True,
    )
    console.print("[green]✓[/green] Public key exported")


def _setup_reprepro(config: dict) -> None:
    """Setup reprepro."""
    console.print("\n[bold]Setting up reprepro...[/bold]")
    
    os.environ["GNUPGHOME"] = str(APT_GPG_HOME)
    
    distributions = f"""Origin: {config["REPO_NAME"]}
Label: {config["REPO_LABEL"]}
Codename: {config["REPO_CODENAME"]}
Architectures: {config["REPO_ARCH"]}
Components: main
Description: {config["REPO_LABEL"]}
SignWith: {config.get("GPG_KEY_ID", "default")}
"""
    (APT_REPO / "conf" / "distributions").write_text(distributions)
    
    options = f"""verbose
basedir {APT_REPO}
gnupghome {APT_GPG_HOME}
ask-passphrase
"""
    (APT_REPO / "conf" / "options").write_text(options)
    
    subprocess.run(["reprepro", "-b", str(APT_REPO), "export"], check=False)
    console.print("[green]✓[/green] reprepro configured")


def _setup_apt_auth(config: dict) -> None:
    """Setup authentication."""
    console.print("\n[bold]Setting up authentication...[/bold]")
    
    htpasswd_file = APT_BASE / ".htpasswd"
    credentials_file = APT_BASE / ".credentials"
    
    if config["ENABLE_AUTH"] != "true":
        console.print("[dim]Authentication disabled (public repository)[/dim]")
        htpasswd_file.unlink(missing_ok=True)
        credentials_file.unlink(missing_ok=True)
        return
    
    subprocess.run([
        "htpasswd", "-bc", str(htpasswd_file),
        config["AUTH_USER"], config["AUTH_PASS"]
    ], check=True, capture_output=True)
    htpasswd_file.chmod(0o600)
    
    credentials_file.write_text(f"""# APT Repository Credentials
USER={config['AUTH_USER']}
PASS={config['AUTH_PASS']}
URL=https://{config['DOMAIN']}
""")
    credentials_file.chmod(0o600)
    
    console.print("[green]✓[/green] Authentication configured")
    console.print(f"\n[yellow]┌─────────────────────────────────────────────────┐[/yellow]")
    console.print(f"[yellow]│  Credentials (save securely!)                   │[/yellow]")
    console.print(f"[yellow]│  Username: {config['AUTH_USER']:<36}│[/yellow]")
    console.print(f"[yellow]│  Password: {config['AUTH_PASS']:<36}│[/yellow]")
    console.print(f"[yellow]└─────────────────────────────────────────────────┘[/yellow]")


def _setup_caddy(config: dict) -> None:
    """Setup Caddy web server."""
    console.print("\n[bold]Setting up Caddy...[/bold]")
    
    enable_auth = config["ENABLE_AUTH"] == "true"
    caddy_hash = None
    
    if enable_auth:
        result = subprocess.run(
            ["caddy", "hash-password", "--plaintext", config["AUTH_PASS"]],
            capture_output=True,
            text=True,
        )
        caddy_hash = result.stdout.strip()
    
    if enable_auth:
        caddyfile = f"""{config["DOMAIN"]} {{
    root * {APT_REPO}
    
    @public {{
        path /key.gpg /key /setup-client.sh /index.html
    }}
    handle @public {{
        file_server
    }}
    
    handle {{
        basicauth {{
            {config["AUTH_USER"]} {caddy_hash}
        }}
        file_server
    }}
    
    log {{
        output file /var/log/caddy/apt-access.log
    }}
}}
"""
    else:
        caddyfile = f"""{config["DOMAIN"]} {{
    root * {APT_REPO}
    file_server browse
    
    log {{
        output file /var/log/caddy/apt-access.log
    }}
}}
"""
    
    Path("/etc/caddy/Caddyfile").write_text(caddyfile)
    Path("/var/log/caddy").mkdir(parents=True, exist_ok=True)
    
    subprocess.run(["systemctl", "enable", "caddy"], check=True)
    subprocess.run(["systemctl", "restart", "caddy"], check=True)
    console.print("[green]✓[/green] Caddy configured (automatic HTTPS)")


def _setup_nginx(config: dict) -> None:
    """Setup Nginx web server."""
    console.print("\n[bold]Setting up Nginx...[/bold]")
    
    Path("/etc/nginx/sites-enabled/default").unlink(missing_ok=True)
    
    enable_auth = config["ENABLE_AUTH"] == "true"
    htpasswd_path = str(APT_BASE / ".htpasswd")
    listen_port = config["LISTEN_PORT"]
    domain = config["DOMAIN"]
    
    if enable_auth:
        nginx_conf = f"""server {{
    listen {listen_port};
    server_name {domain};
    
    root {APT_REPO};
    
    location ~ ^/(key\\.gpg|key|setup-client\\.sh|index\\.html|\\.fancyindex/.*)$ {{
        allow all;
    }}
    
    location / {{
        auth_basic "APT Repository";
        auth_basic_user_file {htpasswd_path};
        
        fancyindex on;
        fancyindex_exact_size off;
        fancyindex_localtime on;
        fancyindex_header "/.fancyindex/header.html";
        fancyindex_footer "/.fancyindex/footer.html";
        fancyindex_show_path off;
        fancyindex_name_length 255;
        fancyindex_time_format "%Y-%m-%d %H:%M";
    }}

    location /dists/ {{
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        auth_basic "APT Repository";
        auth_basic_user_file {htpasswd_path};
    }}
    
    access_log /var/log/nginx/apt-access.log;
    error_log /var/log/nginx/apt-error.log;
}}
"""
    else:
        nginx_conf = f"""server {{
    listen {listen_port};
    server_name {domain};
    
    root {APT_REPO};
    
    location / {{
        fancyindex on;
        fancyindex_exact_size off;
        fancyindex_localtime on;
        fancyindex_header "/.fancyindex/header.html";
        fancyindex_footer "/.fancyindex/footer.html";
        fancyindex_show_path off;
        fancyindex_name_length 255;
        fancyindex_time_format "%Y-%m-%d %H:%M";
    }}

    location /dists/ {{
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }}
    
    access_log /var/log/nginx/apt-access.log;
    error_log /var/log/nginx/apt-error.log;
}}
"""
    
    Path("/etc/nginx/sites-available/apt-repo").write_text(nginx_conf)
    Path("/etc/nginx/sites-enabled/apt-repo").unlink(missing_ok=True)
    Path("/etc/nginx/sites-enabled/apt-repo").symlink_to("/etc/nginx/sites-available/apt-repo")
    
    subprocess.run(["nginx", "-t"], check=True)
    subprocess.run(["systemctl", "enable", "nginx"], check=True)
    subprocess.run(["systemctl", "restart", "nginx"], check=True)
    console.print(f"[green]✓[/green] Nginx configured (port {listen_port})")


def _create_client_files(config: dict) -> None:
    """Create client setup files."""
    console.print("\n[bold]Creating client files...[/bold]")
    
    enable_auth = config["ENABLE_AUTH"] == "true"
    domain = config["DOMAIN"]
    repo_codename = config["REPO_CODENAME"]
    repo_arch = config["REPO_ARCH"]
    
    # setup-client.sh
    if enable_auth:
        client_script = f"""#!/bin/bash
set -e
DOMAIN="{domain}"
CODENAME="{repo_codename}"
AUTH_USER="${{1:?Usage: $0 USERNAME PASSWORD}}"
AUTH_PASS="${{2:?Usage: $0 USERNAME PASSWORD}}"

echo "[1/4] Adding GPG key..."
rm -f /usr/share/keyrings/internal-apt.gpg
curl -fsSL -u "$AUTH_USER:$AUTH_PASS" "https://$DOMAIN/key.gpg" | gpg --dearmor -o /usr/share/keyrings/internal-apt.gpg

echo "[2/4] Configuring authentication..."
mkdir -p /etc/apt/auth.conf.d
cat > /etc/apt/auth.conf.d/internal.conf << EOF
machine $DOMAIN
login $AUTH_USER
password $AUTH_PASS
EOF
chmod 600 /etc/apt/auth.conf.d/internal.conf

echo "[3/4] Adding APT source..."
echo "deb [signed-by=/usr/share/keyrings/internal-apt.gpg] https://$DOMAIN $CODENAME main" > /etc/apt/sources.list.d/internal.list

echo "[4/4] Updating package list..."
apt-get update -qq

echo "Setup complete! Install with: sudo apt install vaultctl"
"""
    else:
        client_script = f"""#!/bin/bash
set -e
DOMAIN="{domain}"
CODENAME="{repo_codename}"

echo "[1/3] Adding GPG key..."
rm -f /usr/share/keyrings/internal-apt.gpg
curl -fsSL "https://$DOMAIN/key.gpg" | gpg --dearmor -o /usr/share/keyrings/internal-apt.gpg

echo "[2/3] Adding APT source..."
echo "deb [signed-by=/usr/share/keyrings/internal-apt.gpg] https://$DOMAIN $CODENAME main" > /etc/apt/sources.list.d/internal.list

echo "[3/3] Updating package list..."
apt-get update -qq

echo "Setup complete! Install with: sudo apt install vaultctl"
"""
    (APT_REPO / "setup-client.sh").write_text(client_script)
    (APT_REPO / "setup-client.sh").chmod(0o755)
    
    # index.html (simplified)
    badge_color = "#f59e0b" if enable_auth else "#10b981"
    badge_text = "Private" if enable_auth else "Public"
    
    index_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>APT Repository - {domain}</title>
    <style>
        body{{font-family:system-ui,sans-serif;max-width:800px;margin:40px auto;padding:20px}}
        h1{{margin-bottom:8px}}
        .badge{{background:{badge_color};color:#fff;padding:4px 12px;border-radius:20px;font-size:12px}}
        .code{{background:#1e1e2e;color:#cdd6f4;padding:16px;border-radius:8px;font-family:monospace;overflow-x:auto}}
        .btn{{display:inline-block;padding:10px 16px;margin:8px 8px 8px 0;border:1px solid #ddd;border-radius:6px;text-decoration:none;color:#333}}
    </style>
</head>
<body>
    <h1>APT Repository <span class="badge">{badge_text}</span></h1>
    <p><a href="/key.gpg" class="btn">GPG Key</a> <a href="/setup-client.sh" class="btn">Setup Script</a></p>
    <h2>Quick Setup</h2>
    <div class="code">curl -fsSL https://{domain}/setup-client.sh | sudo bash{" -s -- USER PASSWORD" if enable_auth else ""}</div>
</body>
</html>
"""
    (APT_REPO / "index.html").write_text(index_html)
    
    # fancyindex templates
    fancyindex_dir = APT_REPO / ".fancyindex"
    fancyindex_dir.mkdir(parents=True, exist_ok=True)
    (fancyindex_dir / "header.html").write_text(f"<h1>APT Repository - {domain}</h1>")
    (fancyindex_dir / "footer.html").write_text("<p>Powered by reprepro</p>")
    
    subprocess.run(["chown", "-R", "www-data:www-data", str(APT_REPO)], check=False)
    console.print("[green]✓[/green] Client files created")


def _apt_full_install(config: dict, web_server: str) -> None:
    """Full APT server installation."""
    console.print("\n[bold]Installing packages...[/bold]")
    
    packages = ["reprepro", "gnupg", "gnupg-agent", "apache2-utils", "curl"]
    if web_server == "caddy":
        _install_caddy()
    else:
        packages.extend(["nginx", "libnginx-mod-http-fancyindex"])
    
    subprocess.run(["apt-get", "update", "-qq"], check=True)
    subprocess.run(["apt-get", "install", "-y", "-qq"] + packages, check=True)
    console.print("[green]✓[/green] Packages installed")
    
    console.print("\n[bold]Creating directories...[/bold]")
    APT_REPO.mkdir(parents=True, exist_ok=True)
    (APT_REPO / "conf").mkdir(exist_ok=True)
    (APT_REPO / "db").mkdir(exist_ok=True)
    (APT_REPO / "dists").mkdir(exist_ok=True)
    (APT_REPO / "pool").mkdir(exist_ok=True)
    APT_GPG_HOME.mkdir(parents=True, exist_ok=True)
    APT_GPG_HOME.chmod(0o700)
    console.print("[green]✓[/green] Directories created")
    
    _setup_apt_gpg(config)
    _save_apt_config(config)
    _setup_reprepro(config)
    _setup_apt_auth(config)
    
    if web_server == "caddy":
        _setup_caddy(config)
    else:
        _setup_nginx(config)
    
    _create_client_files(config)


def _apt_reconfigure(config: dict, web_server: str) -> None:
    """Reconfigure APT server."""
    console.print("\n[bold]Reconfiguring...[/bold]")
    
    os.environ["GNUPGHOME"] = str(APT_GPG_HOME)
    gpg_key_id = _get_gpg_key_id()
    
    if not gpg_key_id:
        console.print("[red]✗[/red] GPG key not found. Run full setup.")
        raise typer.Exit(1)
    
    config["GPG_KEY_ID"] = gpg_key_id
    console.print(f"[green]✓[/green] GPG Key ID: {gpg_key_id}")
    
    _save_apt_config(config)
    _setup_reprepro(config)
    _setup_apt_auth(config)
    
    if web_server == "caddy":
        _setup_caddy(config)
    else:
        _setup_nginx(config)
    
    _create_client_files(config)


def apt_server_setup(reconfigure: bool = False) -> None:
    """Setup APT repository server (interactive)."""
    _check_root("setup apt-server")
    
    apt_config = _load_apt_config()
    
    if reconfigure and not apt_config:
        console.print("[red]✗[/red] APT repository not installed. Run full setup first.")
        raise typer.Exit(1)
    
    if apt_config:
        console.print("[yellow]Existing configuration found[/yellow]")
        console.print(f"  Domain: {apt_config.get('DOMAIN', 'N/A')}")
        console.print(f"  GPG Email: {apt_config.get('GPG_EMAIL', 'N/A')}")
        console.print()
    
    console.print("[bold]Select web server mode[/bold]")
    console.print("  1. Caddy - Standalone with automatic HTTPS")
    console.print("  2. Traefik - Backend for existing Traefik reverse proxy")
    
    existing_ws = apt_config.get("WEB_SERVER", "caddy")
    default_ws = "1" if existing_ws == "caddy" else "2"
    ws_choice = Prompt.ask("\nChoice", choices=["1", "2"], default=default_ws)
    web_server = "caddy" if ws_choice == "1" else "traefik"
    
    domain = Prompt.ask("Domain", default=apt_config.get("DOMAIN", ""))
    if not domain:
        console.print("[red]✗[/red] Domain is required.")
        raise typer.Exit(1)
    
    gpg_email = Prompt.ask("GPG signing email", default=apt_config.get("GPG_EMAIL", ""))
    if not gpg_email:
        console.print("[red]✗[/red] GPG email is required.")
        raise typer.Exit(1)
    
    gpg_name = Prompt.ask("GPG key name", default=apt_config.get("GPG_NAME", "APT Repository Signing Key"))
    repo_name = Prompt.ask("Repository name", default=apt_config.get("REPO_NAME", "internal"))
    repo_codename = Prompt.ask("Distribution codename", default=apt_config.get("REPO_CODENAME", "stable"))
    repo_arch = Prompt.ask("Architecture", default=apt_config.get("REPO_ARCH", "amd64"))
    
    enable_auth = Confirm.ask("Enable authentication?", default=apt_config.get("ENABLE_AUTH", "true") == "true")
    
    auth_user = ""
    auth_pass = ""
    if enable_auth:
        auth_user = Prompt.ask("Auth username", default=apt_config.get("AUTH_USER", "apt"))
        existing_pass = apt_config.get("AUTH_PASS", "")
        auth_pass = Prompt.ask("Password (Enter to auto-generate)", password=True, default="")
        if not auth_pass:
            if existing_pass:
                auth_pass = existing_pass
            else:
                import secrets
                auth_pass = secrets.token_urlsafe(16)
    
    listen_port = 8080
    if web_server == "traefik":
        listen_port = int(Prompt.ask("Nginx listen port", default=str(apt_config.get("LISTEN_PORT", "8080"))))
    
    config = {
        "DOMAIN": domain,
        "GPG_EMAIL": gpg_email,
        "GPG_NAME": gpg_name,
        "REPO_NAME": repo_name,
        "REPO_LABEL": f"{repo_name.title()} Repository",
        "REPO_CODENAME": repo_codename,
        "REPO_ARCH": repo_arch,
        "ENABLE_AUTH": str(enable_auth).lower(),
        "AUTH_USER": auth_user,
        "AUTH_PASS": auth_pass,
        "WEB_SERVER": web_server,
        "LISTEN_PORT": str(listen_port),
    }
    
    if not Confirm.ask("\nProceed with this configuration?"):
        console.print("[dim]Cancelled[/dim]")
        raise typer.Exit(0)
    
    if reconfigure:
        _apt_reconfigure(config, web_server)
    else:
        _apt_full_install(config, web_server)
    
    console.print("\n")
    console.print(Panel.fit(
        f"[bold green]APT Server Setup Complete![/bold green]\n\n"
        f"URL: https://{config['DOMAIN']}\n"
        f"Web Server: {web_server.upper()}\n\n"
        f"Add packages: vaultctl admin repo add <package.deb>",
        title="✓ Complete",
    ))


def apt_client_setup(
    url: str,
    user: Optional[str] = None,
    password: Optional[str] = None,
    codename: str = "stable",
    remove: bool = False,
) -> None:
    """Setup APT client to use repository."""
    _check_root("setup apt-client")
    
    from urllib.parse import urlparse
    parsed = urlparse(url)
    domain = parsed.netloc or parsed.path
    
    if remove:
        console.print(f"[bold]Removing APT client for {domain}...[/bold]")
        Path("/etc/apt/sources.list.d/internal.list").unlink(missing_ok=True)
        Path("/etc/apt/auth.conf.d/internal.conf").unlink(missing_ok=True)
        Path("/usr/share/keyrings/internal-apt.gpg").unlink(missing_ok=True)
        subprocess.run(["apt-get", "update", "-qq"], check=False)
        console.print("[green]✓[/green] APT client configuration removed")
        return
    
    if user and not password:
        password = Prompt.ask("Password", password=True)
    
    console.print("[1/4] Adding GPG key...")
    keyring_path = Path("/usr/share/keyrings/internal-apt.gpg")
    keyring_path.unlink(missing_ok=True)
    
    curl_cmd = ["curl", "-fsSL"]
    if user and password:
        curl_cmd.extend(["-u", f"{user}:{password}"])
    curl_cmd.append(f"{url}/key.gpg")
    
    try:
        result = subprocess.run(curl_cmd, capture_output=True, check=True)
        subprocess.run(["gpg", "--dearmor", "-o", str(keyring_path)], input=result.stdout, check=True)
        console.print("      [green]✓[/green] Done")
    except subprocess.CalledProcessError as e:
        console.print(f"      [red]✗[/red] Failed: {e}")
        raise typer.Exit(1)
    
    if user and password:
        console.print("[2/4] Configuring authentication...")
        auth_dir = Path("/etc/apt/auth.conf.d")
        auth_dir.mkdir(parents=True, exist_ok=True)
        auth_file = auth_dir / "internal.conf"
        auth_file.write_text(f"machine {domain}\nlogin {user}\npassword {password}\n")
        auth_file.chmod(0o600)
        console.print("      [green]✓[/green] Done")
    else:
        console.print("[2/4] Skipping authentication (public repo)")
    
    console.print("[3/4] Adding APT source...")
    sources_file = Path("/etc/apt/sources.list.d/internal.list")
    sources_file.write_text(f"deb [signed-by={keyring_path}] {url} {codename} main\n")
    console.print("      [green]✓[/green] Done")
    
    console.print("[4/4] Updating package list...")
    try:
        subprocess.run(["apt-get", "update", "-qq"], check=True)
        console.print("      [green]✓[/green] Done")
    except subprocess.CalledProcessError:
        console.print("      [yellow]![/yellow] Update failed, but source was added")
    
    console.print(Panel.fit(
        "[bold green]Setup Complete![/bold green]\n\n"
        "Install packages with:\n"
        "  sudo apt install vaultctl",
        title="✓ Complete",
    ))
